name: surrogate-newton-cfd
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy=1.26
  - scipy=1.15
  - h5py=3.13
  - pandas=2.3
  - pyyaml=6.0
  - mpi4py=4.1
  - pip:
      - torch==2.7.1
      - einops==0.8.1
      - tqdm==4.67.1
      - cst-modeling3d==0.2.8
      - -e .[deployment]
