"""Clean NK_resume runtime bridge.

This package starts as a new implementation boundary.  It must not import from
historical runtime packages; un-migrated behavior should raise NotMigratedError.
"""

from __future__ import annotations

from .exceptions import ContractError, LegacyBoundaryError, NKResumeError, NotMigratedError
from .cases import build_direct_case, build_fsb_case, build_resume_case, validate_case
from .geometry import (
    CGNS_REF_SCHEMA,
    WALL_DISTANCE_REF_SCHEMA,
    CGNSRef,
    WallDistanceRef,
    cgns_ref_from_solver_context,
    resolve_cgns_path,
    resolve_cgns_ref,
    resolve_wall_distance,
    wall_distance_ref_from_solver_context,
)
from .metrics import (
    AGGREGATE_METRICS_SCHEMA,
    FIELD_METRICS_SCHEMA,
    FORCE_METRICS_SCHEMA,
    RESIDUAL_METRICS_SCHEMA,
    TRAJECTORY_METRICS_SCHEMA,
    aggregate_results,
    compute_field_force_coefficients,
    field_metrics,
    force_metrics,
    normalize_force_coefficients,
    residual_metrics,
    trajectory_summary,
)
from .orchestration import (
    MANIFEST_RUN_SUMMARY_SCHEMA,
    ManifestRunResult,
    run_manifest,
    write_manifest_run_summary,
)
from .pipeline import (
    ExportResult,
    MPIPoolManifestProjectionResult,
    ManifestProjectionResult,
    NKResumePipeline,
    PipelineResult,
    create_pipeline,
)
from .payload import (
    LEGACY_PROJECTION_REFERENCE_SCHEMA,
    REPLAY_JOB_SCHEMA,
    REPLAY_PLAN_SCHEMA,
    LegacyProjectionReference,
    ReplayJobRequest,
    ReplayPlan,
    plan_replay_manifest,
    read_legacy_projection_reference,
    replay_manifest,
    resume_case_from_payload,
)
from .plans import (
    AdaptiveSchedule,
    CyclePolicy,
    NKWorkPlan,
    PlanKind,
    PredictorKind,
    ResumeMode,
    ResumePlan,
    StagePlan,
    SolverPreset,
    alternating_plan,
    finalonly_plan,
    resume_plan_from_dict,
)
from .schema import (
    FixedLiftContext,
    GeometryContext,
    GroundTruth,
    ModelInputs,
    PredictionState,
    ResumeCase,
    RuntimeState,
    SolverContext,
)
from .solver import (
    PROJECTION_RESULT_SCHEMA,
    PROJECTION_STAGE_RESULT_SCHEMA,
    SOLVER_OPTIONS_SCHEMA,
    ProjectionRequest,
    ProjectionResult,
    ProjectionStageResult,
    ReplayService,
    ResidentWarmPoolController,
    SolverOptions,
    WarmPoolManifestProjectionResult,
    build_solver_options,
    load_projection_result_dict,
    project_manifest_pools,
    project_manifest_warm_pools,
    solver_options_for_plan,
    solver_options_for_stage,
    write_projection_result,
)

__all__ = [
    "AdaptiveSchedule",
    "AGGREGATE_METRICS_SCHEMA",
    "CGNS_REF_SCHEMA",
    "CGNSRef",
    "ContractError",
    "CyclePolicy",
    "ExportResult",
    "FIELD_METRICS_SCHEMA",
    "FixedLiftContext",
    "FORCE_METRICS_SCHEMA",
    "GeometryContext",
    "GroundTruth",
    "LegacyBoundaryError",
    "LEGACY_PROJECTION_REFERENCE_SCHEMA",
    "LegacyProjectionReference",
    "ManifestProjectionResult",
    "MANIFEST_RUN_SUMMARY_SCHEMA",
    "ModelInputs",
    "MPIPoolManifestProjectionResult",
    "ManifestRunResult",
    "NKWorkPlan",
    "NKResumeError",
    "NotMigratedError",
    "NKResumePipeline",
    "PlanKind",
    "PredictionState",
    "PredictorKind",
    "PROJECTION_RESULT_SCHEMA",
    "PROJECTION_STAGE_RESULT_SCHEMA",
    "PipelineResult",
    "ProjectionRequest",
    "ProjectionResult",
    "ProjectionStageResult",
    "REPLAY_JOB_SCHEMA",
    "REPLAY_PLAN_SCHEMA",
    "RESIDUAL_METRICS_SCHEMA",
    "ReplayJobRequest",
    "ReplayPlan",
    "ReplayService",
    "ResidentWarmPoolController",
    "ResumeCase",
    "ResumeMode",
    "ResumePlan",
    "RuntimeState",
    "SOLVER_OPTIONS_SCHEMA",
    "SolverContext",
    "SolverOptions",
    "SolverPreset",
    "StagePlan",
    "TRAJECTORY_METRICS_SCHEMA",
    "WALL_DISTANCE_REF_SCHEMA",
    "WallDistanceRef",
    "WarmPoolManifestProjectionResult",
    "aggregate_results",
    "alternating_plan",
    "build_solver_options",
    "build_direct_case",
    "build_fsb_case",
    "build_resume_case",
    "cgns_ref_from_solver_context",
    "compute_field_force_coefficients",
    "create_pipeline",
    "field_metrics",
    "finalonly_plan",
    "force_metrics",
    "load_projection_result_dict",
    "normalize_force_coefficients",
    "plan_replay_manifest",
    "project_manifest_pools",
    "project_manifest_warm_pools",
    "read_legacy_projection_reference",
    "replay_manifest",
    "resume_case_from_payload",
    "resume_plan_from_dict",
    "residual_metrics",
    "resolve_cgns_path",
    "resolve_cgns_ref",
    "resolve_wall_distance",
    "run_manifest",
    "solver_options_for_plan",
    "solver_options_for_stage",
    "trajectory_summary",
    "validate_case",
    "wall_distance_ref_from_solver_context",
    "write_manifest_run_summary",
    "write_projection_result",
]
